version: 2
updates:
    - package-ecosystem: github-actions
      commit-message:
          include: scope
          prefix: ci
      directory: /
      ignore:
          # Staying on v3 due to incomplete migration guide for v4
          - dependency-name: google-github-actions/release-please-action
            update-types: ["version-update:semver-major"]
      open-pull-requests-limit: 20
      schedule:
          interval: monthly

    - package-ecosystem: npm
      commit-message:
          include: scope
          prefix: build
      directory: /
      groups:
          commitlint:
              patterns:
                  - "@commitlint*"
          eslint:
              patterns:
                  - "eslint*"
          fastify-core:
              patterns:
                  - "@fastify*"
                  - "fastify"
                  - "fastify-plugin"
                  - "fluent-json-schema"
                  - "env-schema"
                  - "secure-json-parse"
      open-pull-requests-limit: 20
      schedule:
          interval: monthly
