name: CI

on:
    push:
        branches:
            - master
        paths-ignore:
            - "docs/**"
            - "*.md"
    pull_request:
        branches:
            - master
        paths-ignore:
            - "docs/**"
            - "*.md"
        types: [opened, ready_for_review, reopened, synchronize]

jobs:
    call-workflow:
        uses: Fdawgs/workflows/.github/workflows/plugins-ci.yml@main
